---
title: "init"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
install.packages("ipumsr")
library(ipumsr)
library(dplyr, warn.conflicts = FALSE)
```

```{r}
# Note that you can pass in the loaded DDI into the `read_ipums_micro()`
usa_ddi <- read_ipums_ddi("usa_00002.xml")
usa_data <- read_ipums_micro(usa_ddi, verbose = FALSE)

#Finding the variables that have a label
usa_data %>%
  select_if(is.labelled)

# Convert the labels to factors (and drop the unused levels)
usa_data2 <- usa_data %>%
  mutate(sex_factor = droplevels(as_factor(SEX)),
         marital_factor=droplevels(as_factor(MARST)),
         newchild_factor=droplevels(as_factor(FERTYR)),
         race_factor= droplevels(as_factor(RACE)),
         hispan_factor= droplevels(as_factor(HISPAN)),
         educ_factor= droplevels(as_factor(EDUC)),
         hinsur_factor= droplevels(as_factor(HCOVANY)),
         degfield_factor= droplevels(as_factor(DEGFIELD)),
         empstat_factor= droplevels(as_factor(EMPSTAT)),
         occ_factor= droplevels(as_factor(OCC)),
         ind_factor= droplevels(as_factor(IND)),
         diffmob_factor=droplevels(as_factor(DIFFMOB)),
         diffcare_factor=droplevels(as_factor(DIFFCARE)),
         vetstat_factor=droplevels(as_factor(VETSTAT)),
         pwstate_factor=droplevels(as_factor(PWSTATE2)),
         tranwork_factor=droplevels(as_factor(TRANWORK))
  )
```
